# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-12 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170512_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='stuends',
            new_name='students',
        ),
    ]
